version: "2"

services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_USER=warius # replace with your username
      - INFLUXDB_USER_PASSWORD=12345678 # replace with your password
      - INFLUXDB_DB=main_storage # replace with your database name
    networks:
      - mynetwork

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - //var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mynetwork

volumes:
  influxdb:
  grafana_data:

networks:
  mynetwork:
